### ISSUE TITLE
Key scripts for reproduction are MISSING

### ISSUE THREAD

**Issue by ZillaRU** [BioCenter-SHU/Multi-SBI#1]
Hello. I have tried to reproduce your methods.
Things went well during data preprocessing and cleaning. But then I found the directory `cnn` (including the key script `cnn_structure.py `) mentioned in the `readme.md` is **missing**.
https://github.com/marinehdk/Multi-SBI/blob/9aa1456d577ea3fa64ce11522ee75aed16e44fba/README.md?plain=1#L74-L79
Can you make this essential script available for reproduction?
Many thanks for considering my request.

**Comment by marinehdk** [comment]
I'm glad that our method can help. It was our negligence that forgetting to upload the CNN folder, mainly due to the large TXT file inside. We have compressed the file and reuploaded it, hoping it can help you.

**Comment by marinehdk** [comment]
I'm glad that our method can help. It was our negligence that forgetting to upload the CNN folder, mainly due to the large TXT file inside. We have compressed the file and reuploaded it, hoping it can help you.
